# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/leap_labs_adversarial_attack.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(893, 624)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background: #FAFAFA;\n"
"}\n"
"\n"
"#widget,  #widget_3, #widget_5{\n"
"background: #FFF;\n"
"border-radius: 15px;\n"
"\n"
"    color: #fff;\n"
"    font-size: 14px;\n"
"    font-family: Poppins;\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    line-height: 100%;\n"
"}\n"
"\n"
"#widget_2,  #widget_4, #frame{\n"
"background: #FFF;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"/* ---------------- Style for QPushButton---------------- */\n"
"\n"
"QPushButton{\n"
"    padding: 3px 7px;\n"
"    border-radius: 10px;\n"
"    background: #4368EB;\n"
"\n"
"    color: #fff;\n"
"    font-size: 14px;\n"
"    font-family: Poppins;\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    line-height: 100%;\n"
"}\n"
"QPushButton:hover{\n"
"    background:  rgba(67, 104, 235, 0.6);\n"
"}\n"
"\n"
"\n"
"/* ---------------- Style for QLineEdit---------------- */\n"
"\n"
"QLineEdit{\n"
"    padding: 2px 7px;\n"
"    \n"
"    border-radius: 5px;\n"
"    border: 1px solid #757575;\n"
"    background: #FFF;\n"
"    \n"
"    color: #1B1E20;\n"
"    font-weight: 500;\n"
"    line-height: 150%;\n"
"}\n"
"\n"
"QTextBrowser{\n"
"    padding: 11px 15px;\n"
"    \n"
"    border-radius: 5px;\n"
"    border: 1px solid #757575;\n"
"    background: #FFF;\n"
"    \n"
"    color: #1B1E20;\n"
"    font-weight: 500;\n"
"    line-height: 150%;\n"
"}\n"
"\n"
"\n"
"/* ---------------- Style for QComboBox ---------------- */\n"
"\n"
"\n"
"QComboBox {\n"
"    border-radius: 5px;\n"
"    border: 1px solid #757575;\n"
"    padding: 2px 5px;\n"
"\n"
"    color: #1B1E20;\n"
"    font-size: 14px;\n"
"    font-family: Poppins;\n"
"    font-weight: 500;\n"
"\n"
"    background-color: #FFF;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFF;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #757575;\n"
"    padding: 3px;\n"
"    color: #1B1E20;\n"
"    selection-background-color: #636a87;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color : #FFFFFF  ;\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background-color : #FFFFFF  ;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-left-width: 0px;\n"
"    border-left-style: solid; \n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icon/Arrow - Down -- Black.svg);\n"
"\n"
"    width: 16px; \n"
"    height: 16px;\n"
"    padding-right : 15px;\n"
"} \n"
"\n"
"\n"
"/* ---------------- Style for QSpinBox ---------------- */\n"
"\n"
"\n"
"QSpinBox {\n"
"    border-radius: 5px;\n"
"    border: 1px solid #757575;\n"
"    padding: 3px 15px;\n"
"\n"
"    color: #1B1E20;\n"
"    font-size: 14px;\n"
"    font-family: Poppins;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right; /* position at the top right corner */\n"
"\n"
"    image: url(:/icon/spin up -- Black.svg);\n"
"    border-width: 1px;\n"
"    padding : 10px 15px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right; /* position at bottom right corner */\n"
"\n"
"    image: url(:/icon/spin down -- Black.svg);\n"
"    border-width: 1;\n"
"    padding : 10px 15px;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.upload_image = QtWidgets.QPushButton(self.widget_2)
        self.upload_image.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.upload_image.setObjectName("upload_image")
        self.gridLayout.addWidget(self.upload_image, 0, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.run_MNIST_classification = QtWidgets.QPushButton(self.widget_4)
        self.run_MNIST_classification.setObjectName("run_MNIST_classification")
        self.gridLayout_2.addWidget(self.run_MNIST_classification, 0, 0, 1, 1)
        self.run_adversarial_attack_and_rerun_MNIST_classification = QtWidgets.QPushButton(self.widget_4)
        self.run_adversarial_attack_and_rerun_MNIST_classification.setObjectName("run_adversarial_attack_and_rerun_MNIST_classification")
        self.gridLayout_2.addWidget(self.run_adversarial_attack_and_rerun_MNIST_classification, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.reset_button = QtWidgets.QPushButton(self.widget_6)
        self.reset_button.setMinimumSize(QtCore.QSize(80, 35))
        self.reset_button.setMaximumSize(QtCore.QSize(85, 35))
        self.reset_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout_3.addWidget(self.reset_button)
        self.verticalLayout.addWidget(self.widget_6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CRISPR-TAPE 2.0"))
        self.label.setText(_translate("MainWindow", "Leap labs adversarial attack ui"))
        self.upload_image.setText(_translate("MainWindow", "Upload image"))
        self.label_4.setText(_translate("MainWindow", "Please upload your image using the upload image button"))
        self.run_MNIST_classification.setText(_translate("MainWindow", "Run MNIST classification"))
        self.run_adversarial_attack_and_rerun_MNIST_classification.setText(_translate("MainWindow", "Run adversarial attack and rerun MNIST classification"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
